apiVersion: kbld.k14s.io/v1alpha1
kind: Config
#! build image
sources:
- image: localhost:5000/hello-app
  path: src
  pack:
    build:
      builder: paketobuildpacks/builder
#! publish (push) image
destinations:
- image: localhost:5000/hello-app
  newImage: localhost:5000/hello-app
