#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: gcr.io/fe-ciberkleid/carvel-demo/hello-app
  path: src
  pack:
    build:
      builder: paketobuildpacks/builder

#@ if/end data.values.helloApp.pushImageTag:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: gcr.io/fe-ciberkleid/carvel-demo/hello-app
  newImage: #@ data.values.helloApp.pushImageTag
