apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
  - path: config/dependencies
    contents:
      - path: redis
        git:
          url: https://github.com/ciberkleid/carvel-demo-redis
          ref: main
        includePaths:
          - redis-*