#@data/values

#! This file contains default config values
#! To override these values, use override files

---
namespace:
  name: carvel-demo
  #! Set to null to omit Namespace resource
  owner: null

redis_address: hello-redis.carvel-demo.svc.cluster.local

helloApp:
  name: hello-app
  message: stranger

  #! Set to null to skip publishing image to registry
  pushImageTag: docker.io/ciberkleid/hello-app

  ingress:
    hostname: null
    domain: null
    class: null
    secret:
      certificate: null
      privateKey: null